### PR TITLE
Break long words into characters

### LINKED ISSUE #55: Try to break lines more accurately.
In English lowercase, sometimes up to half of the box is empty. Space should be better used when possible

### PR DESCRIPTION
**Pull request by saschanaz**
Closes #55

(Actually I think the op of #55 is more about https://github.com/LuisMayo/objection_engine/issues/73#issuecomment-1114305732 rather than the comment below, but anyway...)

### CODE REVIEW

**Comment by saschanaz** [comment]
```
render_comment_list([Comment(text_content="音声合成ソフトVOCALOIDをボーカルに用いたオリジナル楽曲を発表している音楽プロデューサー、ボカロP。別名は蜜柑星P。配偶者はクリエイターの夏背。 ")], output_filename="output.mp4")
```

Before:

image

After:

image

(That overflow should be fixed separately)

**Comment by LuisMayo** [comment]
I'm AFK right now. I'll check in the following days. Thank you very much for the PR, this was something I wanted to do for a while

**Comment by LuisMayo** [comment]
This does NOT close #55 , it only addresses a comment in that issue.
However this works and fix Japanese and other non-whitespace languages so I'm really grateful for that.
Thanks!

**Comment by saschanaz** [comment]
> This does NOT close #55 , it only addresses a comment in that issue. However this works and fix Japanese and other non-whitespace languages so I'm really grateful for that. Thanks!

Does #73 covers that?

**Comment by LuisMayo** [comment]
Well, you opened #73 so you're the one to evaluate whether it's fixed or not. So feel free to close that issue.
I'd think it's fixed yeah

**Comment by saschanaz** [comment]
https://github.com/LuisMayo/objection_engine/pull/74#issuecomment-1114307436 is about #73, and I think that's the only remaining part in #55, or is there anything else?

**Comment by LuisMayo** [comment]
#55 is not about overflow, quite the contrary, sometimes the video split a sentences in two messages even if it would fit in only one message, making messages unnecessary large

**Comment by saschanaz** [comment]
Sounds like that's still about comments_to_scene, fixing one should ideally fix another. But let's keep them for now, thanks!

**Comment by LuisMayo** [comment]
Thank YOU :-)

**Pull request merged**
