### PR TITLE
Judge gavel slam animation

### PR DESCRIPTION
**Pull request by Meorge**
This pull request allows users to play the Judge's gavel slam animation using the new `gavel` command, as described in the [Using the Gavel Slam Effect](https://github.com/Meorge/objection_engine/blob/feat/gavel-slam/docs/UsingGavelSlamEffect.md) document.

https://github.com/LuisMayo/objection_engine/assets/9957987/f530af95-8b51-4bb0-978b-1679edded084

To use this feature, [the `gavel_slam` folder, available for download here](https://drive.google.com/drive/folders/1K-6sSn31_jFoXhnQ7-g52WL6xPet9qWS?usp=sharing), will need to be placed inside the `assets` folder.

### CODE REVIEW

**Comment by LuisMayo** [comment]
Fix conflicts!

**Comment by Meorge** [comment]
Alright, looks like the conflict in the documentation should be fixed now! :)

**Comment by Meorge** [comment]
No worries, I guess that just happens when submitting a bunch of PRs at once haha. Should be all good now I think!

**Comment by LuisMayo** [comment]
Looks good to merge.

As always, terrific job Meorge :)

**Pull request merged**
