### PR TITLE
Improve the docker image

### PR DESCRIPTION
**Pull request by lens0021**
Follows #58

See the below document this includes for the usage:

> ### Rendering a video using Docker
> 
> ``` bash
> cp example.py docker-entrypoint.py
> 
> docker build --tag objection-engine .
> docker run --rm \
>   --volume $(pwd)/docker-entrypoint.py:/app/entrypoint.py:ro \
>   --volume $(pwd)/assets:/app/assets \
>   --volume $(pwd)/outputs:/app/outputs \
>   objection-engine
> ```
> 
> The video will be in the `/outputs` directory.
> 
> You can download Polyglot models by setting `POLYGLOT_MODELS` environment variable and preserve the data by mounting `/root/polyglot_data`:
> 
> ``` bash
> docker run --rm \
>   --volume $(pwd)/docker-entrypoint.py:/app/entrypoint.py:ro \
>   --volume $(pwd)/assets:/app/assets \
>   --volume $(pwd)/outputs:/app/outputs \
>   --volume $(pwd)/polyglot_data:/root/polyglot_data \
>   --env POLYGLOT_MODELS="de fr" \
>   objection-engine
> ```
> 
> Or, you can turn off Polyglot entirely by setting `POLYGLOT=0`:
> ``` bash
> docker run --rm \
>   --volume $(pwd)/docker-entrypoint.py:/app/entrypoint.py:ro \
>   --volume $(pwd)/assets:/app/assets \
>   --volume $(pwd)/outputs:/app/outputs \
>   --env POLYGLOT="0" \
>   objection-engine
> ```

### CODE REVIEW

**Comment by LuisMayo** [comment]
Hi!

Thanks a lot for the Pull Request. I'm looking forward to merging it.
I can't test it yet since I don't have a working docker env right now, but I will test it soon enough.

While I try to test this I have a couple suggestions/petitions for you.
If you check the README.md, you will see that I already have a env variable for disabling sentiment analysis, as specified here:

> #### Settings
> The following environment variables are honored by objection_engine:
> - oe_bypass_sentiment: If on any value other than the empty string, the sentiment analysis is bypassed.

In order to accomplish a more uniform experience. I'd ask you to rename the POLYGLOT environment variable to something more similar to what we already have like `oe_disable_polyglot`.

In the same fasion, I think it would be better to add your new variable to the same "Settings" section of the readme, so all environment variables are listed together.

Regardless this changes, you can still talk about this variable on the docker section of the readme.

Thanks a lot for the request and I hope you can make this changes to complete it.

**Comment by lens0021** [comment]
I think I've reflected on the requested changes at the above commit. Feel free to test this and merge whenever possible, thanks!

**Review by LuisMayo — CHANGES_REQUESTED** [review]
Hi!
I have been testing this merge request, but it unfortunately doesn't work.

I have tested both in docker over Windows as well as in Docker over Linux Mint, this being the result:
```
Traceback (most recent call last):
  File "./entrypoint.py", line 24, in <module>
    render_comment_list(comments, f'./outputs/output-{str(int(time()))}.mp4')
  File "/app/renderer.py", line 25, in render_comment_list
    return anim.comments_to_scene(thread, name_music = music_code, output_filename=output_filename)
  File "/app/anim.py", line 510, in comments_to_scene
    ace_attorney_anim(formatted_scenes, **kwargs)
  File "/app/anim.py", line 385, in ace_attorney_anim
    out.run()
  File "/usr/local/lib/python3.7/site-packages/ffmpeg/_run.py", line 325, in run
    raise Error('ffmpeg', out, err)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
```

It doesn't seem this is working :(
Thanks!

**Comment by lens0021** [comment]
I've rebased this PR so #56 can help you.
I think I have to fix the file path to store videos...
```py
render_comment_list(comments, f'output-{str(int(time()))}.mp4')
```

**Review by LuisMayo — APPROVED** [review]

**Comment by LuisMayo** [comment]
This seems good to go.
Thanks a lot for your contributions to the project.

**Pull request merged**
